version: '3.8'

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "9090:80"
    networks:
      - postgres-network

  app:
    image: 343218222156.dkr.ecr.us-east-1.amazonaws.com/list-app:1.1  # Use the ECR image
    container_name: list-app
    restart: always
    depends_on:
      - postgresdb
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data: # Named volume for database persistence
    driver: local  # Ensuring it's using local storage. This is the default, so it's optional.  # By default, Docker volumes use the local
